export {
  AvatarRenderer,
  avatarAnimationCommands,
  avatarCompanionStates,
  avatarPackageAssets,
  avatarPresenceStateFrom,
  avatarPresenceStates,
  avatarStartupSound,
  fallbackRendererFor,
  getAvatarRendererConfig,
  getLive2DAvatarSurfaceHook,
  isAvatarPresenceState,
  Live2DAvatarSurface,
  live2dAvatarSurfaceHooks,
  mascotSource,
  type AvatarCompanionState,
  type AvatarPresenceState,
  type Live2DAvatarSurfaceHook,
} from "@useplatoai/avatar";
