export {
  AvatarRenderer,
  avatarEyeDirectionFromCursor,
  avatarEyeDirectionNeutral,
  avatarEyeDirectionStyle,
  avatarAnimationCommands,
  avatarCompanionStateForClickReaction,
  avatarCompanionStateFromTestCommand,
  avatarCompanionStates,
  avatarIdleWavePolicy,
  avatarLaunchSequence,
  avatarPackageAssets,
  avatarPresenceStateFrom,
  avatarPresenceStates,
  avatarTestAnimationCommands,
  avatarStartupSound,
  fallbackRendererFor,
  getAvatarRendererConfig,
  getLive2DAvatarSurfaceHook,
  isAvatarPresenceState,
  Live2DAvatarSurface,
  live2dAvatarSurfaceHooks,
  millisecondsUntilNextAvatarIdleWave,
  vendoredVrmAssetContract,
  vrmCapabilityInventory,
  vroidAvatarSource,
  type AvatarTestAnimationCommand,
  type AvatarEyeDirection,
  type AvatarEyeTrackingBounds,
  type AvatarEyeTrackingCursor,
  type AvatarCompanionState,
  type AvatarPresenceState,
  type Live2DAvatarSurfaceHook,
} from "@useplatoai/avatar";
