export {
  AvatarRenderer,
  avatarAnimationCommands,
  avatarCompanionStateForClickReaction,
  avatarCompanionStateFromTestCommand,
  avatarCompanionStates,
  avatarIdleWavePolicy,
  avatarLaunchSequence,
  avatarPackageAssets,
  avatarPresenceStateFrom,
  avatarPresenceStates,
  avatarTestAnimationCommands,
  avatarStartupSound,
  fallbackRendererFor,
  getAvatarRendererConfig,
  getLive2DAvatarSurfaceHook,
  isAvatarPresenceState,
  Live2DAvatarSurface,
  live2dAvatarSurfaceHooks,
  millisecondsUntilNextAvatarIdleWave,
  mascotSource,
  type AvatarTestAnimationCommand,
  type AvatarCompanionState,
  type AvatarPresenceState,
  type Live2DAvatarSurfaceHook,
} from "@useplatoai/avatar";
